const cardData = [
  {
    title: "AEM",
    expertise: "#Expertise - 34",
    projects: "Projects - 12",
    learnmore: "Learn more",
    image: "https://piktoridtemplates.s3.amazonaws.com/Group+59.png",
    bgColor: "#0097AB",
  },
  {
    title: "Figma",
    expertise: "#Expertise - 34",
    projects: "Projects - 12",
    learnmore: "Learn more",
    image: "https://piktoridtemplates.s3.amazonaws.com/Group+59.png",
    bgColor: "#006E74",
  },
  {
    title: "Agile Transformation",
    expertise: "#Expertise - 34",
    projects: "Projects - 12",
    learnmore: "Learn more",
    image: "https://piktoridtemplates.s3.amazonaws.com/Group+59.png",
    bgColor: "#003C52",
  },
  {
    title: "Innovation-Future-ready Technologie",
    expertise: "#Expertise - 34",
    projects: "Projects - 12",
    learnmore: "Learn more",
    image: "https://piktoridtemplates.s3.amazonaws.com/Group+59.png",
    bgColor: "#006E74",
  },
  {
    title: "Automation",
    expertise: "#Expertise - 34",
    projects: "Projects - 12",
    learnmore: "Learn more",
    image: "https://piktoridtemplates.s3.amazonaws.com/Group+59.png",
    bgColor: "#003C52",
  },
  {
    title: "Digital Services",
    expertise: "#Expertise - 34",
    projects: "Projects - 12",
    learnmore: "Learn more",
    image: "https://piktoridtemplates.s3.amazonaws.com/Group+59.png",
    bgColor: "#0097AB",
  },
  {
    title: "Cybersecurity and Risk Management",
    expertise: "#Expertise - 34",
    projects: "Projects - 12",
    learnmore: "Learn more",
    image: "https://piktoridtemplates.s3.amazonaws.com/Group+59.png",
    bgColor: "#006E74",
  },
  {
    title: "Application Modernization",
    expertise: "#Expertise - 34",
    projects: "Projects - 12",
    learnmore: "Learn more",
    image: "https://piktoridtemplates.s3.amazonaws.com/Group+59.png",
    bgColor: "#0097AB",
  },
];
export default cardData;
